#!/bin/sh

APP_NAME=${APP_NAME:-XBoard}
APP_ENV=${APP_ENV:-local}
APP_KEY=${APP_KEY:-base64:PZXk5vTuTinfeEVG5FpYv2l6WEhLsyvGpiWK7IgJJ60=}
APP_DEBUG=${APP_DEBUG:-false}
APP_URL=${APP_URL:-http://localhost}

ADMIN_SETTING_CACHE=${ADMIN_SETTING_CACHE:-60}
LARAVELS_MAX_REQUEST=${LARAVELS_MAX_REQUEST:-1000}
LARAVELS_WORKER_NUM=${LARAVELS_WORKER_NUM:-2}

DB_CONNECTION=${DB_CONNECTION:-mysql}
DB_HOST=${DB_HOST:-127.0.0.1}
DB_PORT=${DB_PORT:-3306}
DB_DATABASE=${DB_DATABASE:-xboard}
DB_USERNAME=${DB_USERNAME:-root}
DB_PASSWORD=${DB_PASSWORD:-root}
# MYSQL_ATTR_SSL_CA=${MYSQL_ATTR_SSL_CA:-/etc/ssl/certs/ca-certificates.crt}

REDIS_HOST=${REDIS_HOST:-127.0.0.1}
REDIS_PASSWORD=
REDIS_PORT=${REDIS_PORT:-6379}

MAIL_DRIVER=${MAIL_DRIVER:-smtp}
MAIL_HOST=${MAIL_HOST:-smtp.mailtrap.io}
MAIL_PORT=${MAIL_PORT:-2525}
MAIL_USERNAME=${MAIL_USERNAME:-null}
MAIL_PASSWORD=${MAIL_PASSWORD:-null}
MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-null}
MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-null}
MAIL_FROM_NAME=${MAIL_FROM_NAME:-null}

MAILGUN_DOMAIN=
MAILGUN_SECRET=

ENABLE_AUTO_BACKUP_AND_UPDATE=${ENABLE_AUTO_BACKUP_AND_UPDATE:-false}
GOOGLE_CLOUD_KEY_FILE=${GOOGLE_CLOUD_KEY_FILE:-config/googleCloudStorageKey.json}
GOOGLE_CLOUD_STORAGE_BUCKET=

INSTALLED=${INSTALLED:-1/www}

cat > /www/.env <<EOF
APP_NAME=$APP_NAME
APP_ENV=$APP_ENV
APP_KEY=$APP_KEY
APP_DEBUG=$APP_DEBUG
APP_URL=$APP_URL

ADMIN_SETTING_CACHE=$ADMIN_SETTING_CACHE
LARAVELS_LISTEN_IP=0.0.0.0
LARAVELS_LISTEN_PORT=80
LARAVELS_HANDLE_STATIC=true
LARAVELS_MAX_REQUEST=$LARAVELS_MAX_REQUEST
LARAVELS_WORKER_NUM=$LARAVELS_WORKER_NUM
LARAVELS_TIMER=true

APP_RUNNING_IN_CONSOLE=true

LOG_CHANNEL=stack

DB_CONNECTION=$DB_CONNECTION
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_DATABASE=$DB_DATABASE
DB_USERNAME=$DB_USERNAME
DB_PASSWORD=$DB_PASSWORD

# MYSQL_ATTR_SSL_CA=$MYSQL_ATTR_SSL_CA

REDIS_HOST=$REDIS_HOST
REDIS_PASSWORD=$REDIS_PASSWORD
REDIS_PORT=$REDIS_PORT

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
QUEUE_CONNECTION=redis

MAIL_DRIVER=$MAIL_DRIVER
MAIL_HOST=$MAIL_HOST
MAIL_PORT=$MAIL_PORT
MAIL_USERNAME=$MAIL_USERNAME
MAIL_PASSWORD=$MAIL_PASSWORD
MAIL_ENCRYPTION=$MAIL_ENCRYPTION
MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS
MAIL_FROM_NAME=$MAIL_FROM_NAME

MAILGUN_DOMAIN=$MAILGUN_DOMAIN
MAILGUN_SECRET=$MAILGUN_SECRET

# google cloud stoage
ENABLE_AUTO_BACKUP_AND_UPDATE=$ENABLE_AUTO_BACKUP_AND_UPDATE
GOOGLE_CLOUD_KEY_FILE=$GOOGLE_CLOUD_KEY_FILE
GOOGLE_CLOUD_STORAGE_BUCKET=$GOOGLE_CLOUD_STORAGE_BUCKET

INSTALLED=$INSTALLED
EOF

/usr/bin/supervisord --nodaemon -c /etc/supervisor/supervisord.conf
